// File: mydebug
//
//Purpose: Contains functions used for debugging.


function myalert(sz) {
    var generator = window.open('', 'name', 'height=400,width=500,menubar=1,toolbar=1,resizable=1,scrollbars=1')

    generator.document.write('<html><head><title>Popup</title>');
    generator.document.write('<link rel="stylesheet" href="style.css">');
    generator.document.write('</head><body>');
    generator.document.write('<p>This page was generated by the main window.</p>');

    generator.document.write('<br/>' + sz);


    generator.document.write('<p><a href="javascript:self.close()"> Close</a> the popup.</p>');
    generator.document.write('</body></html>');
    generator.document.close();
}